modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Name%20Tag%20Tweaks"
logoFile="icon.png"

[[mods]]
modId="nametagtweaks"
version="3.0"
displayName="Name Tag Tweaks"
displayURL="https://curseforge.com/minecraft/mc-mods/name-tag-tweaks"
authors="Rick South"
description='''Adds name tag crafting recipe, /nametag command, and named entities drop their name tag on death.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.nametagtweaks]]
    modId="collective"
    mandatory=true
    versionRange="[6.16,)"
    ordering="NONE"
    side="BOTH"